[project]
name = "mi-proyecto-flet"
version = "0.1.0"
description = "Poke Clicker Game"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet>=0.21.0",
    "mysql-connector-python>=8.2.0",
    "bcrypt>=4.1.2",
    "pydantic>=2.5.0",
    "pydantic[email]>=2.5.0",
    "python-dotenv>=1.0.0",
    "pyjwt>=2.8.0",
]

[project.scripts]
app = "main:main"

[tool.uv]
dev-dependencies = []